-- ── BATCH IDENTIFIERS ─────────────────────────────────────────────────────
-- Every received batch gets a human-readable code `LOT-YYMMDD-NN` (received
-- date + per-tenant per-day sequence) so staff can track/label/scan it, plus an
-- optional `supplier_lot_no` (the manufacturer's printed lot, for recall
-- traceability). The code is generated by a trigger so any insert path gets it.

alter table public.ingredient_batches
  add column if not exists batch_code text,
  add column if not exists supplier_lot_no text;

create or replace function public.set_batch_code()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  d date := coalesce(new.received_date, current_date);
  seq int;
begin
  if new.batch_code is not null and new.batch_code <> '' then
    return new;
  end if;
  select count(*) + 1 into seq
  from public.ingredient_batches b
  where b.tenant_id = new.tenant_id
    and b.received_date = d;
  new.batch_code := 'LOT-' || to_char(d, 'YYMMDD') || '-' || lpad(seq::text, 2, '0');
  return new;
end;
$$;

drop trigger if exists trg_set_batch_code on public.ingredient_batches;
create trigger trg_set_batch_code
  before insert on public.ingredient_batches
  for each row execute function public.set_batch_code();

-- Backfill existing batches.
with numbered as (
  select
    id,
    'LOT-' || to_char(received_date, 'YYMMDD') || '-' ||
      lpad(
        (row_number() over (
          partition by tenant_id, received_date order by id
        ))::text,
        2, '0'
      ) as code
  from public.ingredient_batches
  where batch_code is null
)
update public.ingredient_batches b
set batch_code = n.code
from numbered n
where b.id = n.id;

create unique index if not exists ingredient_batches_code_uniq
  on public.ingredient_batches(tenant_id, batch_code)
  where batch_code is not null;
